import type { Invoice, Customer, AgentAction, RiskReport, ReplayEvent, Policy } from '@/types';

// ─── Invoices ──────────────────────────────────────────────────────────────

export const mockInvoices: Invoice[] = [
  { id: 'INV-090', customerId: 'CUST-010', customerName: 'Metro Infra Projects', amount: 510000, currency: 'INR', issuedDate: '2024-12-03', dueDate: '2025-01-17', status: 'overdue', daysOverdue: 39, amountOutstanding: 510000, risk: 'HIGH', riskScore: 76, riskReasons: ['Customer historically pays late: 5 of 8 invoices overdue', 'Current invoice is 39 days past due', 'Invoice amount ₹5,10,000 above threshold'], description: 'Metro 2025 kickoff' },
  { id: 'INV-091', customerId: 'CUST-009', customerName: 'Sunrise Exports Ltd', amount: 580000, currency: 'INR', issuedDate: '2024-12-08', dueDate: '2025-02-06', status: 'disputed', daysOverdue: 19, amountOutstanding: 580000, risk: 'CRITICAL', riskScore: 88, riskReasons: ['Active dispute raised by customer', 'Customer has 2 prior disputes on record', 'Average payment delay: 22 days', 'Invoice amount ₹5,80,000 above threshold'], description: 'Export 2025 opening order' },
  { id: 'INV-092', customerId: 'CUST-002', customerName: 'Bharat Manufacturing Co', amount: 425000, currency: 'INR', issuedDate: '2024-12-10', dueDate: '2025-01-24', status: 'overdue', daysOverdue: 32, amountOutstanding: 425000, risk: 'HIGH', riskScore: 72, riskReasons: ['Invoice is 32 days overdue', 'Customer has moderate late-payment history', 'Invoice amount above threshold'], description: 'Manufacturing 2025 prep' },
  { id: 'INV-093', customerId: 'CUST-001', customerName: 'Acme Construction Ltd', amount: 310000, currency: 'INR', issuedDate: '2024-12-12', dueDate: '2025-01-11', status: 'overdue', daysOverdue: 45, amountOutstanding: 310000, risk: 'HIGH', riskScore: 79, riskReasons: ['Invoice is 45 days overdue — escalated to CEO', 'Customer historically pays 10–15 days late', '2 payment reminders sent, no response'], description: 'Construction Jan delivery' },
  { id: 'INV-094', customerId: 'CUST-006', customerName: 'Precision Engineers Ltd', amount: 380000, currency: 'INR', issuedDate: '2024-12-15', dueDate: '2025-01-29', status: 'overdue', daysOverdue: 27, amountOutstanding: 380000, risk: 'MEDIUM', riskScore: 54, riskReasons: ['Invoice is 27 days overdue', 'Prior invoices paid on average 8 days late', 'Amount above high-value threshold'], description: 'Precision Q1 2025' },
  { id: 'INV-095', customerId: 'CUST-010', customerName: 'Metro Infra Projects', amount: 495000, currency: 'INR', issuedDate: '2025-01-06', dueDate: '2025-02-20', status: 'overdue', daysOverdue: 5, amountOutstanding: 495000, risk: 'HIGH', riskScore: 68, riskReasons: ['Early days overdue but customer has worsening trend', 'Previous invoice INV-090 still unpaid', 'Amount ₹4,95,000 above threshold'], description: 'Metro project 2025 phase 1' },
  { id: 'INV-096', customerId: 'CUST-009', customerName: 'Sunrise Exports Ltd', amount: 630000, currency: 'INR', issuedDate: '2025-01-10', dueDate: '2025-03-11', status: 'overdue', daysOverdue: 14, amountOutstanding: 630000, risk: 'CRITICAL', riskScore: 91, riskReasons: ['Customer in active dispute on separate invoice INV-091', 'Customer acknowledged delay citing freight dispute', 'Historical late rate 75%', 'Two invoices now open simultaneously'], description: 'Export first quarter 2025' },
  { id: 'INV-097', customerId: 'CUST-002', customerName: 'Bharat Manufacturing Co', amount: 445000, currency: 'INR', issuedDate: '2025-01-14', dueDate: '2025-02-28', status: 'promise_to_pay', daysOverdue: 17, amountOutstanding: 445000, risk: 'MEDIUM', riskScore: 48, riskReasons: ['Active promise to pay by March 7th', 'Customer email confirmed payment is processing'], description: 'Manufacturing Q1 2025' },
  { id: 'INV-098', customerId: 'CUST-001', customerName: 'Acme Construction Ltd', amount: 340000, currency: 'INR', issuedDate: '2025-01-18', dueDate: '2025-02-17', status: 'open', daysOverdue: 0, amountOutstanding: 340000, risk: 'LOW', riskScore: 22, riskReasons: ['Invoice not yet overdue', 'Customer payment confirmed via email'], description: 'Construction 2025 phase 1' },
  { id: 'INV-099', customerId: 'CUST-006', customerName: 'Precision Engineers Ltd', amount: 395000, currency: 'INR', issuedDate: '2025-01-22', dueDate: '2025-03-08', status: 'disputed', daysOverdue: 17, amountOutstanding: 395000, risk: 'HIGH', riskScore: 74, riskReasons: ['Customer disputes pricing — PO mismatch', 'Revised invoice required before payment', 'Amount above threshold'], description: 'Precision manufacturing 2025' },
  { id: 'INV-100', customerId: 'CUST-010', customerName: 'Metro Infra Projects', amount: 520000, currency: 'INR', issuedDate: '2025-02-03', dueDate: '2025-03-20', status: 'overdue', daysOverdue: 5, amountOutstanding: 520000, risk: 'HIGH', riskScore: 71, riskReasons: ['Invoice pending board approval according to customer', 'Two other invoices still unpaid from same customer', 'Amount ₹5,20,000 above threshold'], description: 'Metro infrastructure 2025' },
];

// ─── Customers ─────────────────────────────────────────────────────────────

export const mockCustomers: Customer[] = [
  { id: 'CUST-001', name: 'Acme Construction Ltd', email: 'accounts@acmeconstruction.com', industry: 'Construction', totalOutstanding: 650000, totalOverdue: 310000, avgPaymentDelayDays: 12, latePaymentRate: 38, risk: 'HIGH', lastActivity: '2025-02-20', invoiceCount: 12 },
  { id: 'CUST-002', name: 'Bharat Manufacturing Co', email: 'finance@bharatmfg.com', industry: 'Manufacturing', totalOutstanding: 870000, totalOverdue: 425000, avgPaymentDelayDays: 9, latePaymentRate: 30, risk: 'MEDIUM', lastActivity: '2025-03-01', invoiceCount: 14 },
  { id: 'CUST-003', name: 'Stellar Logistics Pvt Ltd', email: 'ap@stellarlogistics.com', industry: 'Logistics', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 4, latePaymentRate: 8, risk: 'LOW', lastActivity: '2024-09-22', invoiceCount: 8 },
  { id: 'CUST-004', name: 'NovaTech Solutions', email: 'billing@novatech.in', industry: 'Technology', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 2, latePaymentRate: 5, risk: 'LOW', lastActivity: '2024-08-05', invoiceCount: 7 },
  { id: 'CUST-005', name: 'Greenfield Retailers', email: 'accounts@greenfieldretail.com', industry: 'Retail', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 6, latePaymentRate: 12, risk: 'LOW', lastActivity: '2024-07-18', invoiceCount: 6 },
  { id: 'CUST-006', name: 'Precision Engineers Ltd', email: 'finance@precisioneng.com', industry: 'Manufacturing', totalOutstanding: 775000, totalOverdue: 395000, avgPaymentDelayDays: 8, latePaymentRate: 25, risk: 'HIGH', lastActivity: '2025-03-12', invoiceCount: 10 },
  { id: 'CUST-007', name: 'City Healthcare Network', email: 'billing@cityhealthcare.in', industry: 'Healthcare', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 5, latePaymentRate: 10, risk: 'LOW', lastActivity: '2024-08-30', invoiceCount: 8 },
  { id: 'CUST-008', name: 'Apex Distributors', email: 'ap@apexdist.com', industry: 'Logistics', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 7, latePaymentRate: 15, risk: 'LOW', lastActivity: '2024-09-05', invoiceCount: 7 },
  { id: 'CUST-009', name: 'Sunrise Exports Ltd', email: 'accounts@sunriseexports.com', industry: 'Manufacturing', totalOutstanding: 1210000, totalOverdue: 1210000, avgPaymentDelayDays: 22, latePaymentRate: 75, risk: 'CRITICAL', lastActivity: '2025-03-10', invoiceCount: 11 },
  { id: 'CUST-010', name: 'Metro Infra Projects', email: 'finance@metroinfra.in', industry: 'Construction', totalOutstanding: 1525000, totalOverdue: 1525000, avgPaymentDelayDays: 18, latePaymentRate: 60, risk: 'CRITICAL', lastActivity: '2025-03-15', invoiceCount: 12 },
  { id: 'CUST-011', name: 'Digital Frontier Inc', email: 'billing@digitalfrontier.com', industry: 'Technology', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 3, latePaymentRate: 7, risk: 'LOW', lastActivity: '2024-07-28', invoiceCount: 5 },
  { id: 'CUST-012', name: 'Royal Hospitality Group', email: 'accounts@royalhospitality.in', industry: 'Hospitality', totalOutstanding: 0, totalOverdue: 0, avgPaymentDelayDays: 9, latePaymentRate: 18, risk: 'LOW', lastActivity: '2024-08-20', invoiceCount: 6 },
];

// ─── Agent Actions ──────────────────────────────────────────────────────────

export const mockActions: AgentAction[] = [
  { id: 'ACT-001', date: '2025-03-25', invoiceId: 'INV-093', customerId: 'CUST-001', customerName: 'Acme Construction Ltd', recipientTier: 'ceo', action: 'escalation_notice', messageBody: '[INTERNAL — CEO ESCALATION]\n\nInvoice INV-093 for Acme Construction Ltd (₹3,10,000) is 45 days overdue.\nThis requires your direction on next steps.', deliveryMode: 'human_signoff', reason: "Invoice is 45 days overdue — policy rule 'ceo' triggered", policyRule: 'ceo', riskLevel: 'HIGH', riskScore: 79, daysOverdue: 45, amountOutstanding: 310000, status: 'awaiting_review' },
  { id: 'ACT-002', date: '2025-03-24', invoiceId: 'INV-096', customerId: 'CUST-009', customerName: 'Sunrise Exports Ltd', recipientTier: 'sales', action: 'escalation_notice', messageBody: '[INTERNAL — SALES ESCALATION]\n\nInvoice INV-096 for Sunrise Exports Ltd (₹6,30,000) is 14 days overdue. Customer has acknowledged delay.', deliveryMode: 'human_signoff', reason: "Invoice is 14 days overdue — policy rule 'sales' triggered", policyRule: 'sales', riskLevel: 'CRITICAL', riskScore: 91, daysOverdue: 14, amountOutstanding: 630000, status: 'awaiting_review', emailIntent: 'payment_delay' },
  { id: 'ACT-003', date: '2025-03-23', invoiceId: 'INV-091', customerId: 'CUST-009', customerName: 'Sunrise Exports Ltd', recipientTier: 'internal', action: 'route_human_review', messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nInvoice INV-091: Dispute detected. Customer claims services not yet delivered.', deliveryMode: 'human_signoff', reason: 'Dispute detected — automated collection paused pending resolution', policyRule: 'dispute_hold', riskLevel: 'CRITICAL', riskScore: 88, daysOverdue: 19, amountOutstanding: 580000, status: 'awaiting_review', emailIntent: 'dispute' },
  { id: 'ACT-004', date: '2025-03-22', invoiceId: 'INV-095', customerId: 'CUST-010', customerName: 'Metro Infra Projects', recipientTier: 'customer', action: 'payment_reminder', messageBody: 'Dear Metro Infra Projects,\n\nThis is a friendly reminder that invoice INV-095 for ₹4,95,000 is currently outstanding.\n\nPlease let us know if payment has already been arranged.\n\nBest regards,\nCollectIQ Collections Team', deliveryMode: 'auto_send', reason: "Invoice is 1 day overdue — policy rule 'first_reminder' triggered", policyRule: 'first_reminder', riskLevel: 'HIGH', riskScore: 68, daysOverdue: 1, amountOutstanding: 495000, status: 'auto_sent' },
  { id: 'ACT-005', date: '2025-03-21', invoiceId: 'INV-092', customerId: 'CUST-002', customerName: 'Bharat Manufacturing Co', recipientTier: 'controller', action: 'escalation_notice', messageBody: '[INTERNAL — CONTROLLER ESCALATION]\n\nINV-092 (₹4,25,000) has been escalated to Controller after Sales follow-up was ineffective.', deliveryMode: 'human_signoff', reason: "Invoice is 29 days overdue — policy rule 'controller' triggered", policyRule: 'controller', riskLevel: 'HIGH', riskScore: 72, daysOverdue: 29, amountOutstanding: 425000, status: 'approved' },
  { id: 'ACT-006', date: '2025-03-20', invoiceId: 'INV-099', customerId: 'CUST-006', customerName: 'Precision Engineers Ltd', recipientTier: 'internal', action: 'route_human_review', messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nInvoice INV-099: Customer disputes pricing — PO mismatch. Revised invoice needed.', deliveryMode: 'human_signoff', reason: 'Dispute detected — automated collection paused', policyRule: 'dispute_hold', riskLevel: 'HIGH', riskScore: 74, daysOverdue: 12, amountOutstanding: 395000, status: 'awaiting_review', emailIntent: 'dispute' },
  { id: 'ACT-007', date: '2025-03-19', invoiceId: 'INV-094', customerId: 'CUST-006', customerName: 'Precision Engineers Ltd', recipientTier: 'sales', action: 'escalation_notice', messageBody: '[INTERNAL — SALES ESCALATION]\n\nINV-094 (₹3,80,000) is 20 days past due. Please contact your account relationship at Precision.', deliveryMode: 'human_signoff', reason: "Invoice is 20 days overdue — policy rule 'sales' triggered", policyRule: 'sales', riskLevel: 'MEDIUM', riskScore: 54, daysOverdue: 20, amountOutstanding: 380000, status: 'rejected' },
  { id: 'ACT-008', date: '2025-03-18', invoiceId: 'INV-100', customerId: 'CUST-010', customerName: 'Metro Infra Projects', recipientTier: 'customer', action: 'payment_reminder', messageBody: 'Dear Metro Infra Projects,\n\nThis is a follow-up regarding invoice INV-100 for ₹5,20,000 which is now 3 days overdue.', deliveryMode: 'human_signoff', reason: "Invoice is 3 days overdue — amount above threshold → human sign-off required", policyRule: 'first_reminder', riskLevel: 'HIGH', riskScore: 71, daysOverdue: 3, amountOutstanding: 520000, status: 'awaiting_review' },
];

// ─── Risk Report ────────────────────────────────────────────────────────────

export const mockRiskReport: RiskReport[] = [
  { invoiceId: 'INV-096', customerId: 'CUST-009', customerName: 'Sunrise Exports Ltd', amount: 630000, amountOutstanding: 630000, dueDate: '2025-03-11', daysOverdue: 14, riskLevel: 'CRITICAL', riskScore: 91, reasons: ['Customer historically pays late: 6 of 8 invoices overdue (75%)', 'Active dispute on separate invoice INV-091 — customer non-cooperative', 'Average payment delay: 22 days across historical invoices', 'Two invoices now open simultaneously (₹12,10,000 total exposure)', 'Customer acknowledged delay citing external freight dispute'], features: { historical_late_rate: 75, avg_days_late: 22, current_overdue_days: 14, broken_promises: 1, previous_disputes: 2, reminders_sent: 2, worsening_behavior: 1 } },
  { invoiceId: 'INV-091', customerId: 'CUST-009', customerName: 'Sunrise Exports Ltd', amount: 580000, amountOutstanding: 580000, dueDate: '2025-02-06', daysOverdue: 49, riskLevel: 'CRITICAL', riskScore: 88, reasons: ['Active dispute raised by customer claiming services not delivered', 'Invoice 49 days overdue — in dispute, automation halted', 'Customer has 2 prior disputes on record', 'Customer historically pays late 75% of the time'], features: { historical_late_rate: 75, avg_days_late: 22, current_overdue_days: 49, broken_promises: 1, previous_disputes: 2, reminders_sent: 3, worsening_behavior: 1 } },
  { invoiceId: 'INV-100', customerId: 'CUST-010', customerName: 'Metro Infra Projects', amount: 520000, amountOutstanding: 520000, dueDate: '2025-03-20', daysOverdue: 5, riskLevel: 'HIGH', riskScore: 71, reasons: ['Three invoices now open from Metro Infra simultaneously', 'Total Metro Infra exposure: ₹15,25,000', 'Customer citing board approval delays', 'Historical late payment rate 60%'], features: { historical_late_rate: 60, avg_days_late: 18, current_overdue_days: 5, broken_promises: 0, previous_disputes: 0, reminders_sent: 1, worsening_behavior: 1 } },
  { invoiceId: 'INV-093', customerId: 'CUST-001', customerName: 'Acme Construction Ltd', amount: 310000, amountOutstanding: 310000, dueDate: '2025-01-11', daysOverdue: 69, riskLevel: 'HIGH', riskScore: 79, reasons: ['Invoice 69 days overdue — CEO escalation triggered', '2 reminders sent with no response', 'Customer historically pays 12 days late on average', 'Amount ₹3,10,000 above high-value threshold'], features: { historical_late_rate: 38, avg_days_late: 12, current_overdue_days: 69, broken_promises: 0, previous_disputes: 0, reminders_sent: 3, worsening_behavior: 0 } },
  { invoiceId: 'INV-099', customerId: 'CUST-006', customerName: 'Precision Engineers Ltd', amount: 395000, amountOutstanding: 395000, dueDate: '2025-03-08', daysOverdue: 17, riskLevel: 'HIGH', riskScore: 74, reasons: ['Active pricing dispute — customer claims PO mismatch', 'Collection halted pending revised invoice', 'Amount ₹3,95,000 above threshold'], features: { historical_late_rate: 25, avg_days_late: 8, current_overdue_days: 17, broken_promises: 0, previous_disputes: 1, reminders_sent: 1, worsening_behavior: 0 } },
];

// ─── Replay Events ──────────────────────────────────────────────────────────

export const mockReplayEvents: ReplayEvent[] = [
  { id: 'R-001', date: '2024-02-05', invoiceId: 'INV-001', customerName: 'Acme Construction Ltd', action: 'payment_reminder', recipientTier: 'customer', deliveryMode: 'auto_send', reason: "Invoice is 1 day overdue — 'first_reminder' triggered", policyRule: 'first_reminder', riskLevel: 'LOW', riskScore: 12, daysOverdue: 1, amountOutstanding: 185000, messageBody: 'Dear Acme Construction Ltd, This is a friendly reminder regarding invoice INV-001 for ₹1,85,000 (Construction materials supply Q1) which was due on 2024-02-04 and remains outstanding.' },
  { id: 'R-002', date: '2024-02-06', invoiceId: 'INV-001', customerName: 'Acme Construction Ltd', action: 'promise_recorded', recipientTier: 'customer', deliveryMode: 'auto_send', reason: 'Customer replied with promise to pay — reminders paused', policyRule: 'promise_active', riskLevel: 'LOW', riskScore: 12, daysOverdue: 2, amountOutstanding: 185000, messageBody: 'Promise to pay recorded. Collections paused until promise date.' },
  { id: 'R-003', date: '2024-04-02', invoiceId: 'INV-018', customerName: 'Precision Engineers Ltd', action: 'route_human_review', recipientTier: 'internal', deliveryMode: 'human_signoff', reason: 'Dispute detected — quantity discrepancy reported by customer', policyRule: 'dispute_hold', riskLevel: 'MEDIUM', riskScore: 45, daysOverdue: 10, amountOutstanding: 190000, messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nInvoice INV-018: Dispute detected. Customer reports quantity discrepancy (500 vs 470 units billed).' },
  { id: 'R-004', date: '2024-05-20', invoiceId: 'INV-022', customerName: 'Sunrise Exports Ltd', action: 'route_human_review', recipientTier: 'internal', deliveryMode: 'human_signoff', reason: 'Customer requested a payment plan — requires human approval', policyRule: 'payment_plan_review', riskLevel: 'MEDIUM', riskScore: 52, daysOverdue: 13, amountOutstanding: 380000, messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nSunrise Exports Ltd has requested a payment plan for INV-022 (₹3,80,000).' },
  { id: 'R-005', date: '2024-07-22', invoiceId: 'INV-047', customerName: 'Metro Infra Projects', action: 'promise_recorded', recipientTier: 'customer', deliveryMode: 'auto_send', reason: 'Customer promised payment by July 25th — reminders paused', policyRule: 'promise_active', riskLevel: 'MEDIUM', riskScore: 38, daysOverdue: 20, amountOutstanding: 335000, messageBody: 'Promise to pay recorded for INV-047. Collections paused until 2024-07-25.' },
  { id: 'R-006', date: '2024-09-25', invoiceId: 'INV-070', customerName: 'Sunrise Exports Ltd', action: 'escalation_notice', recipientTier: 'sales', deliveryMode: 'human_signoff', reason: "Invoice is 25 days overdue — 'sales' escalation triggered", policyRule: 'sales', riskLevel: 'HIGH', riskScore: 68, daysOverdue: 25, amountOutstanding: 510000, messageBody: '[INTERNAL — SALES ESCALATION]\n\nINV-070 for Sunrise Exports (₹5,10,000) is 25 days overdue. Customer cites overseas payment delays.' },
  { id: 'R-007', date: '2024-11-20', invoiceId: 'INV-076', customerName: 'Sunrise Exports Ltd', action: 'route_human_review', recipientTier: 'internal', deliveryMode: 'human_signoff', reason: 'Dispute detected on INV-076 — items 3 and 4 not yet delivered', policyRule: 'dispute_hold', riskLevel: 'CRITICAL', riskScore: 82, daysOverdue: 15, amountOutstanding: 575000, messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nSunrise Exports disputes INV-076 claiming services not yet delivered.' },
  { id: 'R-008', date: '2025-01-22', invoiceId: 'INV-090', customerName: 'Metro Infra Projects', action: 'route_human_review', recipientTier: 'internal', deliveryMode: 'human_signoff', reason: 'Customer querying invoice scope — routed for human review', policyRule: 'invoice_question', riskLevel: 'HIGH', riskScore: 71, daysOverdue: 5, amountOutstanding: 510000, messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nMetro Infra queries INV-090 scope alignment before processing payment.' },
  { id: 'R-009', date: '2025-02-10', invoiceId: 'INV-091', customerName: 'Sunrise Exports Ltd', action: 'route_human_review', recipientTier: 'internal', deliveryMode: 'human_signoff', reason: 'Customer proposed payment plan — requires human approval', policyRule: 'payment_plan_review', riskLevel: 'CRITICAL', riskScore: 88, daysOverdue: 4, amountOutstanding: 580000, messageBody: '[INTERNAL — HUMAN REVIEW REQUIRED]\n\nSunrise Exports proposes installment plan: ₹3,00,000 by Feb 28 and ₹2,80,000 by Mar 31.' },
  { id: 'R-010', date: '2025-03-01', invoiceId: 'INV-092', customerName: 'Bharat Manufacturing Co', action: 'escalation_notice', recipientTier: 'sales', deliveryMode: 'human_signoff', reason: "Invoice is 36 days overdue — 'controller' triggered; promise-to-pay received but unverified", policyRule: 'sales', riskLevel: 'HIGH', riskScore: 72, daysOverdue: 36, amountOutstanding: 425000, messageBody: '[INTERNAL — SALES ESCALATION]\n\nINV-092 (₹4,25,000) is 36 days overdue. Customer mentioned payment by March 7th but no confirmation yet.' },
];

// ─── Dashboard Chart Data ───────────────────────────────────────────────────

export const mockReceivablesTrend = [
  { month: 'Sep 24', outstanding: 2850000, overdue: 420000 },
  { month: 'Oct 24', outstanding: 3120000, overdue: 580000 },
  { month: 'Nov 24', outstanding: 2940000, overdue: 490000 },
  { month: 'Dec 24', outstanding: 3680000, overdue: 720000 },
  { month: 'Jan 25', outstanding: 4250000, overdue: 1080000 },
  { month: 'Feb 25', outstanding: 5100000, overdue: 1840000 },
  { month: 'Mar 25', outstanding: 4820000, overdue: 2135000 },
];

export const mockRiskDistribution = [
  { name: 'LOW', value: 0, color: '#10b981' },
  { name: 'MEDIUM', value: 1, color: '#f59e0b' },
  { name: 'HIGH', value: 6, color: '#ef4444' },
  { name: 'CRITICAL', value: 3, color: '#8b5cf6' },
];

// ─── Policy ─────────────────────────────────────────────────────────────────

export const mockPolicy: Policy = {
  reminders: {
    first_reminder: { overdue_days: 1, recipient_tier: 'customer', mode: 'auto_send', frequency_days: null },
    second_reminder: { overdue_days: 7, recipient_tier: 'customer', mode: 'auto_send', frequency_days: null },
    third_reminder: { overdue_days: 14, recipient_tier: 'customer', mode: 'auto_send', frequency_days: null },
  },
  escalation: {
    sales: { overdue_days: 21, recipient_tier: 'sales', mode: 'human_signoff', frequency_days: 7 },
    controller: { overdue_days: 35, recipient_tier: 'controller', mode: 'human_signoff', frequency_days: 14 },
    ceo: { overdue_days: 50, recipient_tier: 'ceo', mode: 'human_signoff', frequency_days: null },
    owner: { overdue_days: 65, recipient_tier: 'owner', mode: 'human_signoff', frequency_days: null },
  },
  human_review: {
    triggers: ['dispute', 'payment_plan_request', 'legal_language', 'low_confidence', 'ambiguous_invoice', 'high_amount'],
    high_amount_threshold: 300000,
    low_confidence_threshold: 0.70,
  },
};
